version: "3"
services:
  ipsec:
    image: ipsec-client:1.0.0
    container_name: ipsec-client
    build:
      dockerfile: ./Dockerfile
      tags:
        - "ipsec-client:1.0.0"
    privileged: true
    restart: ${RESTART_MODE:-unless-stopped}
#    healthcheck:
#      test: ["CMD","ip link show | grep -q "ppp0""]
#      interval: 30s
#      timeout: 10s
#      retries: 3
    environment:
      - VPN_IPSEC_PSK=$VPN_IPSEC_PSK
      - VPN_USER=$VPN_USER
      - VPN_PASSWORD=$VPN_PASSWORD
      - VPN_PUBLIC_IP=$VPN_PUBLIC_IP
      - VPN_SERVER_IPV4_ROUTES=$VPN_SERVER_IPV4_ROUTES
    volumes:
      - /var/run/dbus:/var/run/dbus
    network_mode: "host"
