version: "3"
services:
  ipsec:
    image: ipsecvpn-client:1.0.0
    container_name: ipsec-client
    build:
      dockerfile: ./Dockerfile
      tags:
        - "ipsecvpn-client:1.0.0"
    restart: ${RESTART_MODE:-unless-stopped}
    environment:
      - VPN_IPSEC_PSK=$VPN_IPSEC_PSK
      - VPN_USER=$VPN_USER
      - VPN_PASSWORD=$VPN_PASSWORD
      - VPN_PUBLIC_IP=$VPN_PUBLIC_IP
      - VPN_LOCAL_IP=$VPN_LOCAL_IP
    volumes:
      - ./ipsecvpn/conf:/ipsecvpn/etc
    networks:
      - ipsec-network   
networks:
  ipsec-network:
    external: true
    driver: bridge
    name: ipsec-network
